spring:
  # log 색상
  output.ansi.enabled : always
  ### secret information
  profiles.include : info
  # auto DOL
  jpa:
    hibernate.ddl-auto : create
    # SQL 쿼리 확인
    properties.hibernate.format_sql: true
    # OSIV false로 둬서 DB conn 유지 최소화
    open-in-view : false
  # 공용 메시지 / 에러 메시지 구분.
  messages.basename: messages,errors
# for debug
logging.level.toy1.upload_toy : DEBUG
