spring:
  # log 색상
  output.ansi.enabled : always
  ### DB
  profiles.include : info
  # auto DOL
  jpa:
    hibernate.ddl-auto : create
    # SQL 쿼리 확인
    properties.hibernate.format_sql: true
    # 확장성을 위해
    open-in-view : false
  # 공용 메시지 / 에러 메시지 구분.
  messages.basename: messages,errors
# for debug
logging.level.toy1.upload_toy : DEBUG

  # 저장 파일 경로
file.dir : /C:/upload_test/
